In [1]:
#import dependencies
import numpy as np

#Creating a matrix

In [2]:
matrix1 = np.array([[2, 3],[6, 7]])
print(matrix1)

[[2 3]
 [6 7]]


In [3]:
matrix1.shape

(2, 2)

In [4]:
matrix2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [6]:
print(matrix2)
matrix2.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

creating matrix with random value

In [9]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.15672728 0.12003134 0.96383319]
 [0.08883962 0.53376033 0.09661829]
 [0.70265529 0.35566774 0.18315888]]


In [10]:
#matrix with random integer
random_int_matrix = np.random.randint(2, 10, size = (3, 3))
print(random_int_matrix)

[[7 2 8]
 [5 7 2]
 [4 4 3]]


In [11]:
#matrix with all value 1
matrix_3 = np.ones((3,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
#integer matrix with all value 1
matrix_3 = np.ones((3,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Null matrix

In [12]:
#matrix with all value 0
matrix_4 = np.zeros((3,3))
print(matrix_4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#integer matrix with all value 0
matrix_4 = np.zeros((3,3), dtype = int)
print(matrix_4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Identity matrix

In [16]:
identity = np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of a matrix

In [18]:
rand_matrix = np.random.randint(2, 10, size = (3, 3))
print(rand_matrix)
transpose = np.transpose(rand_matrix)
print(transpose)

[[9 9 2]
 [5 9 9]
 [6 2 3]]
[[9 5 6]
 [9 9 2]
 [2 9 3]]


Matrix addition

In [19]:
a = np.array([[1, 3],[4, 7]])
b = np.array([[3, 5],[2, 4]])

c = a + b
print(c)

[[ 4  8]
 [ 6 11]]


Subtraction of matrix

In [20]:
sub = a - b
print(sub)

[[-2 -2]
 [ 2  3]]


Matrix multiplication

In [21]:
x = 5
y = np.random.randint(10, size = (3, 3))
print(y)

[[3 1 4]
 [4 0 2]
 [4 1 8]]


In [22]:
prod = np.multiply(x, y)
print(prod)

[[15  5 20]
 [20  0 10]
 [20  5 40]]


In [23]:
a = np.random.randint(10, size = (3, 3))
b = np.random.randint(10, size = (3, 3))
print(a)
print(b)

[[5 2 4]
 [7 8 9]
 [3 5 5]]
[[0 9 2]
 [6 3 5]
 [0 4 9]]


In [24]:
prod = np.multiply(a, b)
print(prod)

[[ 0 18  8]
 [42 24 45]
 [ 0 20 45]]


In [37]:
a = np.random.randint(10, size = (3, 3))
b = np.random.randint(10, size = (3, 4))
print(a)
print(b)

[[5 8 5]
 [8 0 6]
 [4 6 7]]
[[8 3 2 5]
 [7 6 9 0]
 [0 4 8 4]]


In [38]:
prod = np.dot(a, b)
print(prod)

[[ 96  83 122  45]
 [ 64  48  64  64]
 [ 74  76 118  48]]


element wise matrix multiplicaton

In [39]:
a = np.random.randint(10, size = (3, 3))
b = np.random.randint(10, size = (3, 4))
print(a)
print(b)

[[2 4 2]
 [7 3 4]
 [3 0 4]]
[[1 1 4 4]
 [9 4 0 6]
 [1 2 8 8]]


In [40]:
prod = np.multiply(a, b)
print(prod)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

to use multiply both matrix should ne in smae shape

In [41]:
a = np.random.randint(10, size = (3, 3))
b = np.random.randint(10, size = (3, 3))
print(a)
print(b)

[[7 5 9]
 [0 3 5]
 [7 5 0]]
[[0 9 3]
 [7 8 5]
 [0 9 5]]


In [42]:
prod = np.multiply(a, b)
print(prod)

[[ 0 45 27]
 [ 0 24 25]
 [ 0 45  0]]
